#!/usr/bin/env bash

echo 'Generating Training Features...'

.. / .. / feature_extraction / main.py .. / .. / data / pan_2015 trainingFeatures \
    - -corpus brown \
    - -master - file trainingMaster  \
    - -char - n - gram 2 3 4 5 - -char - n - gram - size 50 \
    - -word - n - gram 2 3 4 5 - -word - n - gram - size 50 \
    - -postag - n - gram 2 3 4 5 - -postag - n - gram - size 50 \
    - -special - n - gram 2 3 - -special - n - gram - size 5 \
    - -word - frequencies 50


echo 'Generating Testing Features...'

.. / .. / feature_extraction / main.py .. / .. / data / pan_2015_test testFeatures \
    - -corpus brown \
    - -char - n - gram 2 3 4 5 - -char - n - gram - size 50 \
    - -word - n - gram 2 3 4 5 - -word - n - gram - size 50 \
    - -postag - n - gram 2 3 4 5 - -postag - n - gram - size 50 \
    - -special - n - gram 2 3 - -special - n - gram - size 5 \
    - -word - frequencies 50

echo 'Generating Model...'

.. / .. / machine_learning / forest.py trainingFeatures trainingMaster - -split 1.0 \
    - -trees 100

echo 'Making Predictions'

. / panchofy.py testFeatures trainingMaster
