#!/usr/bin/env bash

echo "Generating Features"
./genFeatures

echo 'Generating Model...'

../../machine_learning/forest.py trainingFeatures --split 1.0 \
    --trees 1000 --method minus --iterations 1

echo 'Making Predictions'

./predict.py testFeatures
